# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Foodie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



#Firebase for Database 


    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'

    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
#    source 'https://github.com/CocoaPods/Specs.git
    pod 'GoogleMaps'


# for chat room database
pod 'Firebase/RemoteConfig'


    pod 'YelpAPI'

  # Pods for Foodie

end

