# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'
#source 'https://github.com/CocoaPods/Specs.git
target 'Foodie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'GoogleMaps'
    pod 'YelpAPI', '~> 2.0'
    pod 'BrightFutures', '~> 5.1'
    pod 'AFNetworking', '~> 2.4'
    pod 'BDBOAuth1Manager'
    pod 'SVPullToRefresh'

  # Pods for Foodie

end

